language: cpp
compiler:
- gcc

dist: trusty
sudo: required

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y --no-install-recommends lcov doxygen

before_script:
- "./scripts/travis-prep.sh"

script:
- "./scripts/travis-build.sh"

after_success:
- "./scripts/travis-deploy.sh"

env:
  global:
    # GitHub API key
    secure: IgEqSxCmnFUJoGTnHZxzNGcNerSN8MOkIXdbF/cUmBo2oBo70nMVoMo1Y6PMiEnI5pzaAbpzYP59ZDV/OF2OLcrFTZ+OlVTLUzy4TfCAX8rgju8v+1AN9VOjvqqaB1qdfk4vwjCrTrkkrlolrvMb10aXKo/OGEO7AEH8bpzAFoBCskA/e2wxKjYjGI6dUlzE+lmxfIfthfMyNQo2zT6NhKDllp0wV+s/P84egMsfIjvMHRtKWpO89/dqt8x4+gzZyy0g2K6hW6GLJgIaR5U9HGG69vtqs+TjObjcN7kjGMG7XNLr8ostFSK8upqBhDQeNu4RJSILv8P+lO8PL45ktnfIV0wwA+sVLGLozFvPPJCfypodg+K3/AcP+jlyobgys2LaGmSjKH9iR/xNi/uN54NTBrh5a/M2EeANhMVVdSFlt9dOOhXKk4J/wCoBNqJniVFz0UzgJMIu+S2BD7wlzwXnLrf234E1K6TitrgCRDdcByRwIqit1rY3uaospu8bQNHfbcqhTIGvzXecxqorfk4sifRY2lZzMYgUJGIDMig6RgfL0poIK5Q83yJA1EyikSnr9R6PMO/L/p9YeCY4DDzH6lZzz4nBHERqn5i7c0VvpzkcZtJZPCttrzUpdsxL03STqemsO3DD53KG71G+7um/DEGuBMO/7RZgY48iX8U=
