language: cpp

compiler:
- clang
- gcc

script:
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Debug -DCOMPILE_TESTS=ON -DCOMPILE_WITH_COVERAGE=ON .. && make && make test

after_success:
- make present_coverage && bash <(curl -s https://codecov.io/bash)
- make doc
