language: cpp

compiler:
- clang
- gcc

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y lcov doxygen

script:
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Debug -DCOMPILE_TESTS=ON -DCOMPILE_WITH_COVERAGE=ON .. && make && make test

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    make present_coverage
    make doc
    cd "$TRAVIS_BUILD_DIR"
    mkdir web_push
    cd web_push
    git clone --depth 1 https://github.com/jhartz/present.git -b gh-pages
    cd present
    rm -rf coverage doc
    cp -R ../../coverage ../../doc .
    git add coverage doc
    git -c user.name=travis -c user.email=travis commit -m "Travis doc commit"
    # Make sure to make the output quiet, or else the API token will leak!
    git push -q https://jhartz:$GITHUB_API_KEY@github.com/jhartz/present gh-pages &2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
